
version: 2

groups:
  - name: qteam
    owner:
      name: quality_team
      email: example@gmail.com

models:
    - name: my_first_dbt_model
      group: qteam
      access: public
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this atsableaaaa"
            tests:
                - unique

    - name: my_second_dbt_model
      group: qteam
      access: private
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null