# .github/workflows/run-release-notes.yml
name: Use Release Notes Workflow

on:
  push:
    branches: [test-rename-main]

jobs:
  call-shared:
    uses: TimKlense/release-notes/blob/main/.github/workflows/generate-release-notes.yml@main
    with:
      repo: TimKlense/release-notes
      branch: main
      days: 1
      dry_run: false
